services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: logdrain-postgres
    environment:
      POSTGRES_USER: logdrain
      POSTGRES_PASSWORD: logdrain123
      POSTGRES_DB: logdrain_db
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: logdrain-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  python-ml:
    build:
      context: ../python-ml
      dockerfile: Dockerfile
    container_name: logdrain-python-ml
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://logdrain:logdrain123@postgres:5432/logdrain_db
    depends_on:
      - postgres
    volumes:
      - ../python-ml:/app

volumes:
  postgres_data:
  redis_data: